# Generated by Django 5.1.2 on 2024-12-06 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrandeEcole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('localisation', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Universite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('localisation', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InformationSupplementaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('inscription', "Étapes d'inscription"), ('frais', 'Frais de scolarité'), ('diplome', 'Diplômes délivrés'), ('diplome_requis', "Diplômes requis pour l'admission"), ('contact', 'Contact')], max_length=50)),
                ('contenu', models.TextField()),
                ('universite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informations', to='chatbot.universite')),
            ],
        ),
        migrations.CreateModel(
            name='Composante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('faculte', 'Faculté'), ('institut', 'Institut')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('universite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composantes', to='chatbot.universite')),
            ],
        ),
    ]
