# Generated by Django 5.1.2 on 2024-12-06 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('faculte', 'Faculté'), ('institut', 'Institut'), ('ecole', 'École')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('universite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etablissements', to='chatbot.universite')),
            ],
        ),
        migrations.DeleteModel(
            name='Composante',
        ),
    ]
