# Generated by Django 5.1.2 on 2024-12-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_rename_composante_filiere_etablissement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filiere',
            name='duree',
            field=models.IntegerField(blank=True, help_text='Durée en années', null=True),
        ),
    ]
