# Generated by Django 5.1.2 on 2024-12-12 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_alter_filiere_duree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationsupplementaire',
            name='universite',
        ),
        migrations.AddField(
            model_name='informationsupplementaire',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informations', to='chatbot.filiere'),
        ),
    ]
